const data = [
    {
        id: "1",
        category: "Videos",
        title: "Haz tus propias formas geométricas",
        image: "../assets/img/formasgeometricas.png",
        duration: "8:18",
        date: "16 Febrero 2023",
        views: "362",
        comments: "27",
        
    },
    {
        id: "2",
        category: "Videos",
        title: "La comunicación",
        image: "../assets/img/lacomunicacion.png",
        duration: "12:18",
        date: "5 Mayo 2023",
        views: "162",
        comments: "5",
    },
    {
        id: "3",
        category: "Videos",
        title: "Antiguo Egipto",
        image: "../assets/img/elantiguoegipto.png",
        duration: "8:18",
        date: "28 Abril 2023",
        views: "459",
        comments: "12",
    },
    {
        id: "4",
        category: "Videos",
        title: "El arte",
        image: "../assets/img/art.png",
        duration: "5:18",
        date: "4 Marzo 2023",
        views: "459",
        comments: "30",
    },
    {
        id: "5",
        category: "Artículos",
        title: "Los Pingüinos",
        description: "Descripción del tema",
        image: "../assets/img/lospinguïnos.svg",
        date: "4 Marzo 2023",
        participants: "27",
        },
    {
        id: "6",
        category: "Artículos",
        title: "Los Planetas",
        description: "Descripción del tema",
        image: "../assets/img/losPlanetas.svg",
        date: "4 Marzo 2023",
        participants: "10",
    },
    {
        id: "7",
        category: "Artículos",
        title: "Las Plantas",
        description: "Descripción del tema",
        image: "../assets/img/lasPlantas.svg",
        date: "4 Marzo 2023",
        participants: "15",
    },
    {
        id: "8",
        category: "Artículos",
        title: "Las Plantas",
        author: "Autor",
        description: "Descripción del tema",
        image: "../assets/img/lasPlantas.svg",
        date: "4 Marzo 2023",
       
    },
    {
        id: "9",
        category: "Videos",
        title: "Importancia de la comunicación",
        image: "../assets/img/mano-sujetando-megafono-fondo-rojo.jpg",
        duration: "8:18",
        date: "21 febrero 2023",
        views: "204",
        comments: "31",
        
    },
    {
        id: "10",
        category: "Videos",
        title: "Comunicación efectiva",
        image: "../assets/img/retrato-joven-globo.jpg",
        duration: "8:18",
        date: "04 Agosto 2023",
        views: "103",
        comments: "17",
        
    },
    {
        id: "11",
        category: "Videos",
        title: "Comunicación digital",
        image: "../assets/img/disposicion-simbolos-redes-sociales.jpg",
        duration: "8:18",
        date: "20 Julio 2023",
        views: "111",
        comments: "8",
        
    },
    {
        id: "12",
        category: "Artículos",
        title: "La comunicación",
        author: "Autor",
        description: "Descripción del tema",
        image: "../assets/img/lacomunicacion.png",
        date: "5 Mayo 2023",
       

    },
    {
        id: "13",
        category: "Artículos",
        title: "De dónde vienen las Estrellas",
        author: "Autor",
        description: "Descripción del tema",
        image: "../assets/img/estrella.jpg",
        date: "5 Mayo 2023",
       

    },
    {
        id: "14",
        category: "Temas de conversación",
        title: "Pingüino Emperador",
        author: "Autor",
        description: "Descripción del tema",
        image: "../assets/img/primer-plano-vertical-pinguino-rey-pie-suelo-cubierto-nieve.jpg",
        date: "25 Mayo 2023",
        participants: "17",
    }
    

]